"""One-shot: create the dd-mongo-app, dd-mysql-app, dd-redis-app envs in
the connected Domino. Idempotent — if an env with the canonical name
already exists, it adds a new revision instead of creating a duplicate.

Run from the wizard workspace (so $DOMINO_USER_API_KEY + the in-pod proxy
are wired up):

    python3 scripts/build_engine_envs.py

The three builds run in parallel in Domino's build cluster (~5 min each).
The script prints env IDs immediately and polls until each build is
either Succeeded or Failed.
"""

from __future__ import annotations

import os
import sys
import time
from pathlib import Path

# Resolve repo root regardless of where the script is invoked from.
REPO = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO))

import requests  # noqa: E402
import domino_api as dapi  # noqa: E402

ENGINES = ["mongo", "mysql", "redis"]
PROXY = "http://localhost:8899"
HEADERS = {"X-Domino-Api-Key": dapi.API_KEY,
           "Content-Type": "application/json"}


def log(msg: str) -> None:
    print(f"[envs {time.strftime('%H:%M:%S')}] {msg}", flush=True)


def default_dse_image() -> str:
    r = requests.get(
        f"{PROXY}/v4/environments/defaultEnvironment",
        headers=HEADERS, timeout=20,
    )
    r.raise_for_status()
    base = r.json().get("base") or {}
    img = base.get("dockerImage")
    if not img:
        raise SystemExit("could not find dockerImage on defaultEnvironment.base")
    return img


def find_existing(canonical_name: str) -> str | None:
    for e in dapi.list_environments():
        if isinstance(e, dict) and e.get("name") == canonical_name:
            return e.get("id")
    return None


def create_env(name: str, image: str) -> str:
    # "Global" requires EditEnvironment role which most users don't have
    # via API. "Private" works for the calling user and the env still
    # appears in /v1/environments for projects they own. An admin can
    # promote to Global in the UI if cross-org sharing is desired.
    body = {
        "name": name,
        "visibility": "Private",
        "image": image,
        "addBaseDependencies": True,
    }
    r = requests.post(
        f"{PROXY}/api/environments/beta/environments",
        headers=HEADERS, json=body, timeout=30,
    )
    if r.status_code >= 400:
        raise SystemExit(
            f"create {name} failed: HTTP {r.status_code} {r.text[:500]}"
        )
    env = r.json().get("environment", {})
    eid = env.get("id")
    if not eid:
        raise SystemExit(f"create {name} returned no id: {r.text[:300]}")
    return eid


def add_revision(env_id: str, name: str, image: str, dockerfile: str) -> str:
    body = {
        "dockerfileInstructions": dockerfile,
        "environmentVariables": [],
        "image": image,
        "postRunScript": "",
        "postSetupScript": "",
        "preRunScript": "",
        "preSetupScript": "",
        "skipCache": False,
        "summary": f"dd-{name}-app baseline — generated by build_engine_envs.py",
        "supportedClusters": [],
        "tags": [],
        "useVpn": False,
        "workspaceTools": [],
    }
    r = requests.post(
        f"{PROXY}/api/environments/beta/environments/{env_id}/revisions",
        headers=HEADERS, json=body, timeout=60,
    )
    if r.status_code >= 400:
        raise SystemExit(
            f"add_revision {env_id} failed: HTTP {r.status_code} {r.text[:500]}"
        )
    rev = r.json()
    # Body shape varies by build — try a few keys.
    return (rev.get("revision") or {}).get("id") or rev.get("id") or ""


def revision_status(env_id: str) -> str:
    """Returns 'Queued' / 'Building' / 'Succeeded' / 'Failed' / unknown."""
    r = requests.get(
        f"{PROXY}/v1/environments",
        headers=HEADERS, timeout=20,
    )
    r.raise_for_status()
    for e in r.json().get("data", []):
        if e.get("id") == env_id:
            return ((e.get("latestRevision") or {}).get("status")) or "Unknown"
    return "NotFound"


def build_one(engine: str, image: str) -> tuple[str, str]:
    """Returns (env_id, action)."""
    canonical = f"dd-{engine}-app"
    df_path = REPO / "envs" / canonical / "Dockerfile"
    if not df_path.exists():
        raise SystemExit(f"missing {df_path}")
    dockerfile = df_path.read_text()

    existing = find_existing(canonical)
    if existing:
        log(f"{canonical}: env exists ({existing}) — adding new revision")
        add_revision(existing, engine, image, dockerfile)
        return existing, "revised"

    log(f"{canonical}: creating fresh env")
    env_id = create_env(canonical, image)
    log(f"  → {env_id}; queuing initial revision with our Dockerfile")
    # The create endpoint already kicks off rev #1 with a bare Dockerfile.
    # We add our real Dockerfile as rev #2 so it builds with the engine
    # software installed.
    add_revision(env_id, engine, image, dockerfile)
    return env_id, "created"


def main() -> int:
    log(f"using Domino proxy {PROXY}")
    if not dapi.API_KEY:
        raise SystemExit("DOMINO_USER_API_KEY not set in this workspace")

    image = default_dse_image()
    log(f"DSE base image: {image}")

    results: dict[str, str] = {}
    for engine in ENGINES:
        env_id, action = build_one(engine, image)
        results[engine] = env_id
        log(f"{engine}: env_id={env_id} ({action})")

    log("")
    log("polling for build completion (each build ~3–5 min)…")
    pending = dict(results)
    deadline = time.time() + 25 * 60  # 25 min budget for all builds
    while pending and time.time() < deadline:
        time.sleep(20)
        for engine, env_id in list(pending.items()):
            status = revision_status(env_id)
            log(f"  {engine:6s}  status={status}")
            if status == "Succeeded":
                pending.pop(engine)
            elif status == "Failed":
                log(f"  !! {engine} build FAILED — env id {env_id} "
                    f"(check the Domino UI for revision logs)")
                pending.pop(engine)

    log("")
    log("=" * 56)
    log("BUILD SUMMARY")
    log("=" * 56)
    for engine, env_id in results.items():
        status = revision_status(env_id)
        log(f"  {engine:6s}  {env_id}  {status}")
    log("")
    log("The wizard auto-resolves these by name on /api/config — no")
    log("project env-var setup needed. Reload the wizard UI to see the")
    log("engine cards switch from 'missing env' to enabled.")
    return 0 if not pending else 1


if __name__ == "__main__":
    sys.exit(main())
