"""One-shot: create the dd-mongo-app, dd-mysql-app, dd-redis-app envs in
the connected Domino. Idempotent — if an env with the canonical name
already exists, it adds a new revision instead of creating a duplicate.

Run from the wizard workspace (so $DOMINO_USER_API_KEY + the in-pod proxy
are wired up):

    python3 scripts/build_engine_envs.py

The three builds run in parallel in Domino's build cluster (~5 min each).
The script prints env IDs immediately and polls until each build is
either Succeeded or Failed.
"""

from __future__ import annotations

import sys
import time
from pathlib import Path

# Resolve repo root regardless of where the script is invoked from.
REPO = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO))

import domino_api as dapi  # noqa: E402

ENGINES = ["mongo", "mysql", "redis"]


def log(msg: str) -> None:
    print(f"[envs {time.strftime('%H:%M:%S')}] {msg}", flush=True)


def build_one(engine: str, image: str) -> tuple[str, str]:
    """Returns (env_id, action)."""
    canonical = f"dd-{engine}-app"
    df_path = REPO / "envs" / canonical / "Dockerfile"
    if not df_path.exists():
        raise SystemExit(f"missing {df_path}")
    dockerfile = df_path.read_text()

    existing = dapi.find_environment_by_name(canonical)
    if existing:
        log(f"{canonical}: env exists ({existing}) — adding new revision")
        dapi.add_environment_revision(
            existing, dockerfile, image,
            summary=f"dd-{engine}-app baseline — generated by build_engine_envs.py",
        )
        return existing, "revised"

    log(f"{canonical}: creating fresh env")
    env_id = dapi.create_environment(canonical, image)
    log(f"  → {env_id}; queuing initial revision with our Dockerfile")
    dapi.add_environment_revision(
        env_id, dockerfile, image,
        summary=f"dd-{engine}-app baseline — generated by build_engine_envs.py",
    )
    return env_id, "created"


def main() -> int:
    log(f"using Domino proxy {dapi.PROXY_URL}")
    if not dapi.API_KEY:
        raise SystemExit("DOMINO_USER_API_KEY not set in this workspace")

    image = dapi.default_environment_image()
    log(f"DSE base image: {image}")

    results: dict[str, str] = {}
    for engine in ENGINES:
        env_id, action = build_one(engine, image)
        results[engine] = env_id
        log(f"{engine}: env_id={env_id} ({action})")

    log("")
    log("polling for build completion (each build ~3–5 min)…")
    pending = dict(results)
    deadline = time.time() + 25 * 60  # 25 min budget for all builds
    while pending and time.time() < deadline:
        time.sleep(20)
        for engine, env_id in list(pending.items()):
            rev = dapi.environment_latest_revision(env_id)
            status = rev.get("status", "Unknown")
            log(f"  {engine:6s}  status={status}")
            if status == "Succeeded":
                pending.pop(engine)
            elif status == "Failed":
                log(f"  !! {engine} build FAILED — env id {env_id} "
                    f"(check the Domino UI for revision logs)")
                pending.pop(engine)

    log("")
    log("=" * 56)
    log("BUILD SUMMARY")
    log("=" * 56)
    for engine, env_id in results.items():
        rev = dapi.environment_latest_revision(env_id)
        status = rev.get("status", "Unknown")
        log(f"  {engine:6s}  {env_id}  {status}")
    log("")
    log("The wizard auto-resolves these by name on /api/config — no")
    log("project env-var setup needed. Reload the wizard UI to see the")
    log("engine cards switch from 'missing env' to enabled.")
    return 0 if not pending else 1


if __name__ == "__main__":
    sys.exit(main())
